[package]
name = "envl-cli"
version = "0.3.0"
description = "envl's cli"
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
default-run = "envl"

[[bin]]
name = "envl"
path = "src/cli.rs"

[dependencies]
clap.workspace = true
envl.workspace = true

[lints]
workspace = true
