[package]
name = "envl-cli"
version.workspace = true
description = "envl-cli provides a better .env"
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true
default-run = "envl"

[[bin]]
name = "envl"
path = "src/main.rs"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
clap.workspace = true
envl.workspace = true

[lints]
workspace = true
