[package]
name = "envl"
version.workspace = true
description = "load .envl and .envlconf"
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]

[dependencies]
envl-config.workspace = true
envl-vars.workspace = true
envl-utils.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true
