[package]
name = "envl-vars"
version.workspace = true
description = "parser and lexer for .envl file."
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]

[dependencies]
envl-utils.workspace = true
