name: CI

on:
  pull_request:

jobs:
  envl:
    name: Build Envl
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install tools
        run: rustup component add clippy rustfmt

      - name: Check build
        run: scripts/build-release.sh

      - name: Test
        run: scripts/test.sh

      - name: Lint with clippy
        run: scripts/lint.sh

      - name: Check formatting
        run: scripts/fmt.sh

  devcontainer:
    name: DevContainer
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Checkout docker
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/${{ github.repository }}
          push: never
          runCmd: scripts/ci.sh
