name: CI

on:
  pull_request:
  push:

jobs:
  envl:
    name: Build Envl
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Cache cargo registry
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Checkout Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install tools
        run: |
            rustup component add clippy rustfmt
            npm i -g bun @antfu/ni

      - name: Install npm packages
        run: bun install --frozen-lockfile

      - name: Check build
        run: scripts/build-release.sh

      - name: Test
        run: scripts/test.sh

      - name: Lint with clippy
        run: scripts/lint.sh

      - name: Check formatting
        run: scripts/fmt.sh

  devcontainer:
    name: DevContainer
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Checkout docker
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/${{ github.repository }}
          push: never
          runCmd: |
            ./INSTALL
            ./scripts/ci.sh

  version:
    name: Version Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Checkout Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Packages
        run: bun ci

      - name: Check Version
        run: |
          bun run scripts/envl-version.ts
          bun run scripts/cli-version.ts

  cli:
    name: Cli build check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/envl-cli

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Cache cargo registry
        uses: actions/cache@v5
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Checkout Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: .node-version

      - name: Checkout Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install Packages (workspace)
        working-directory: ./
        run: bun ci

      - name: Install Packages
        run: npm ci

      - name: Build Cli
        run: npm run build

      - name: Check Linting
        run: npm run lint
