name: CI

on:
  pull_request:
  push:

jobs:
  envl:
    name: Build Envl
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/workflows/setup

      - name: Check build
        run: scripts/build-release.sh

      - name: Test
        run: scripts/test.sh

      - name: Lint with clippy
        run: scripts/lint.sh

      - name: Check formatting
        run: scripts/fmt.sh

  devcontainer:
    name: DevContainer
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Checkout docker
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/${{ github.repository }}
          push: never
          runCmd: |
            ./INSTALL
            ./scripts/ci.sh

  version:
    name: Version Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/workflows/setup

      - name: Install Packages
        run: bun ci

      - name: Check Version
        run: |
          bun run scripts/envl-version.ts
          bun run scripts/cli-version.ts

  cli:
    name: Cli build check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/workflows/setup

      - name: Install Packages (workspace)
        run: bun ci

      - name: Check Linting
        working-directory: ./packages/envl-cli
        run: npm run lint

  publish:
    name: Publish
    runs-on: ubuntu-latest
    needs: [envl, version, cli]

    permissions:
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/workflows/setup

      - name: Tag check
        continue-on-error: true
        id: tag-check
        shell: bash
        run: |
          [[ '${{ github.ref }}' == refs/tags/v+([0-9])\.+([0-9])\.+([0-9])*([a-zA-Z]) ]]

      - name: Publish crates.io
        if: steps.tag-check.outcome == 'success'
        run: cargo publish --workspace --exclude envl-rs-test
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      - name: Publish npmjs.com
        if: steps.tag-check.outcome == 'success'
        working-directory: ./packages/envl-cli
        run: |
          npm ci
          npm build
          npm publish --provenance --access public
