name: CI

on:
  pull_request:
  push:

jobs:
  envl:
    name: Build Envl
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/workflows/setup

      - name: Check build
        run: scripts/build-release.sh

      - name: Test
        run: scripts/test.sh

      - name: Lint with clippy
        run: scripts/lint.sh

      - name: Check formatting
        run: scripts/fmt.sh

  devcontainer:
    name: DevContainer
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Checkout docker
        uses: devcontainers/ci@v0.3
        with:
          cacheFrom: ghcr.io/${{ github.repository }}
          push: never
          runCmd: |
            ./INSTALL
            ./scripts/ci.sh

  version:
    name: Version Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/workflows/setup

      - name: Install Packages
        run: bun ci

      - name: Check Version
        run: |
          bun run scripts/envl-version.ts
          bun run scripts/cli-version.ts

  cli:
    name: Cli build check
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./packages/envl-cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup
        uses: ./.github/workflows/setup

      - name: Install Packages (workspace)
        working-directory: ./
        run: bun ci

      - name: Install Packages
        run: npm ci

      - name: Build Cli
        run: npm run build

      - name: Check Linting
        run: npm run lint
